# Generated by Django 2.1 on 2018-08-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='origindate',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
