# Generated by Django 2.1 on 2018-08-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0002_question_origindate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentid', models.IntegerField()),
                ('ownuserid', models.IntegerField()),
                ('content', models.TextField()),
                ('score', models.IntegerField()),
                ('commentcount', models.IntegerField()),
                ('creationdate', models.DateTimeField(auto_now=True)),
                ('origindate', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'eos_answer',
            },
        ),
    ]
