# Generated by Django 2.1 on 2018-08-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentid', models.IntegerField()),
                ('ownuserid', models.IntegerField()),
                ('content', models.TextField()),
                ('score', models.IntegerField()),
                ('commentcount', models.IntegerField()),
                ('creationdate', models.DateTimeField(auto_now=True)),
                ('origindate', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'eth_answer',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.IntegerField()),
                ('ownuserid', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('score', models.IntegerField()),
                ('viewcount', models.IntegerField()),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('answercount', models.IntegerField()),
                ('creationdate', models.DateTimeField(auto_now=True)),
                ('origindate', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'eth_question',
                'ordering': ['-pk'],
            },
        ),
    ]
